# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nantingol' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nantingol
  
  pod 'Firebase/Core'
  pod 'Firebase/Data'
  pod 'GoogleMLKit/Translate', '1.6.0'
  pod 'GoogleMLKit/LanguageID', '2.6.0'
end
